# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61a838ff9027970f76d86a6fd763ce76059310d16f008e7acf712bf5f87a0f6c8393b2229277a50d572227c2bc50c36a2bbca6399123eac01d61a33a56f0494d

test:
  secret_key_base: 39510336176d40671cd90a5413839d5c18cb0b7b1f5a892c16f47bbaea8f3900b4bfd2716ed53ca898e59184733678ef25ac0a713b082f02e3cda0fdac4ac74d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
